# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'ios-client' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for bluemix-object-storage-sample2
  pod 'BMSCore'
  pod 'BMSSecurity'
  pod 'SwiftyJSON'

end
